# CircleCI 2.0
#
version: 2
jobs:
  build:
    docker:
      - image: opspresso/builder
    steps:
      - checkout
      - run:
          name: Publish
          command: |
            bash ./publish.sh
